### ISSUE TITLE
with open(...) as ...

### ISSUE THREAD

**Issue by paulin-mipt** [AnnNesterenko/ann_nesterenko_review1#1]
https://github.com/AnnNesterenko/ann_nesterenko_review1/blob/1bd6d8f18d572c5ee6840d619235371bd1df13a5/train.py#L52

os.path.join -- это очень хорошо и правильно!

Но все файлы нужно открывать через контекстный менеджер, да

**Comment by AnnNesterenko** [comment]
вроде все исправила
