### ISSUE TITLE
dict -> defaultdict

### ISSUE THREAD

**Issue by paulin-mipt** [AnnNesterenko/ann_nesterenko_review1#3]
Чтобы не проверять наличие ключей, можно заменить dict на defaultdict(lambda: defaultdict(int))

P.S. Для сохранения этой конструкции в pickle придется сконвертировать его обратно в dict, но это не страшно

**Comment by AnnNesterenko** [comment]
Ключи в глобальной модели - тоже словари, там ничего не прибавлялось по единичке, поэтому не стала их делать дефолтными. 
defaultdict-ами стали словари, которые являются ключами в глобальной модели, т.к в этих словарях по значению уже хранятся частоты сочетаний слово1-слово2, тут это довольно удобно
